version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: cargo build
  test:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: cargo test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
